# Generated by Django 6.0 on 2026-02-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact_number',
            new_name='mobile',
        ),
    ]
