# Generated by Django 6.0 on 2026-03-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_contact_number_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_records', to='libraryapp.book'),
        ),
    ]
